version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: exampleuser
      POSTGRES_DB: exampledp
    ports:
      - "666:666"
    volumes:
      - postgres_data:/var/lib/postgressql/data


  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_data: 